pola-rs/r-polars

- src/rust/Cargo.lock
- src/rust/Cargo.toml
- src/rust/src/lib.rs
> jemalloc(linux) else mimallac as py-polars

- .github/workflows/check.yaml
- DESCRIPTION
Based on discussion https://github.com/pola-rs/r-polars/issues/14#issuecomment-1379472243
> Add R CMD check workflow

- R/csv.R
> fix csv null value

- DESCRIPTION
- NEWS.md
- R/csv.R
- man/clone_env_one_level_deep.Rd
- man/lazy_csv_reader.Rd
> Fix doc for arg `infer_schema_length `

- DESCRIPTION
- NEWS.md
- README.md
Some additional updates due to package name change.
> chore: additional updates due to package name change

- R/expr__expr.R
- R/extendr-wrappers.R
- R/groupby.R
- R/lazyframe__lazy.R
- R/series__series.R
- src/rust/src/lazy/dataframe.rs
- src/rust/src/lazy/dsl.rs
- src/rust/src/utils/mod.rs
- tests/testthat/test-dataframe.R
- tests/testthat/test-expr.R
- tests/testthat/test-lazy.R
add missing robj_to!(u8, _)  conversion and migrate use of extendr conversion + test
> add robj_to!(u8, _)

- NEWS.md
Single line commit to add NEWS item for PR #107
> NEWS: S3 methods

- README.Rmd
- README.md
Fix small typo in README to fix Issue #130
> Typo in README

- .github/workflows/pkgdown.yaml
> ci: run pkgdown workflow every commits on main branch

- DESCRIPTION
> chore: Increment version number to 0.5.0.9000

- R/extendr-wrappers.R
- R/s3_methods.R
> chore: move some functions to another file

- .github/workflows/check.yaml
> hotfix windows 4.3 rtools

- .github/workflows/release.yaml
hotfix windows compilation by disabling in main workflow
> disable winbuild in release.yaml

- R/s3_methods.R
- tests/testthat/test-s3_methods.R
`[.DataFrame` returns Series when the width is 1 by default.
> feat: `[.DataFrame`'s `drop` param

- R/lazy_functions.R
- man/col.Rd
- tests/testthat/test-dataframe.R
> Positional arguments: pl$col("a", "b", "c")

- .github/workflows/check.yaml
- .github/workflows/release.yaml
add back windows check + release (rtools linker issue is now fixed)
add ubuntu oldrel-1
disable installlog printing step for now as it can crash for some new platforms
> Update check + release platforms

- R/s3_methods.R
- tests/testthat/test-s3_methods.R
Implements @eitsupi 's feature request in https://github.com/pola-rs/r-polars/issues/159
> Negative integers in df[]

- R/construction.R
- R/convert.R
- man/pl-cash-from_arrow.Rd
trying out styler.equals. Seems nice.
uses https://github.com/sorhawell/styler.equals which adds a rstudio addin
highly based on previous work by robinlovelace and lorenzwalthert
> WIP: try styler.equals on files

- docs/docs/stylesheets/extra.css
- docs/mkdocs.orig.yml
* Add footnotes handling (cf #182)
* Fix color theme for "back to top" button and scrollbars in code blocks
> Add footnotes handling in docs

- DESCRIPTION
- NEWS.md
> Increment version number to 0.6.0.9000

- .github/workflows/check.yaml
https://github.com/smorimoto/tune-github-hosted-runner-network
> try smorimoto/tune-github-hosted-runner-network

- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- Makefile
- src/Makevars.ucrt
- src/Makevars.win
- src/rust/rust-toolchain
> fix: pin the rust toolchain version

- .github/actions/setup/action.yaml
- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- Makefile
- src/rust/rust-toolchain
> pin rust night in release.yaml (follow up #217)

- Makefile
- R/dataframe__frame.R
- R/extendr-wrappers.R
- R/zzz.R
- man/nanoarrow.Rd
- src/rust/src/arrow_interop/to_rust.rs
- src/rust/src/concurrent.rs
- src/rust/src/conversion_r_to_s.rs
- src/rust/src/conversion_s_to_r.rs
- src/rust/src/lazy/dataframe.rs
- src/rust/src/lazy/dsl.rs
- src/rust/src/lib.rs
- src/rust/src/rdataframe/mod.rs
- src/rust/src/rdataframe/read_csv.rs
- src/rust/src/rdataframe/read_ipc.rs
- src/rust/src/rdataframe/read_parquet.rs
- src/rust/src/rdatatype.rs
- src/rust/src/rlib.rs
- src/rust/src/series.rs
- src/rust/src/utils/extendr_concurrent.rs
- src/rust/src/utils/mod.rs
- tests/testthat/test-dataframe.R
> Fix rustanalyzer warnings + obey clippy

- flake.lock
- flake.nix
- man/nanoarrow.Rd
This PR updates the flake file and its lock file so that the latest commit can be built in a Nix environment.
> Update nix flake

- DESCRIPTION
- NEWS.md
- R/dataframe__frame.R
- R/extendr-wrappers.R
- R/lazyframe__lazy.R
- man/DataFrame_unique.Rd
- man/LazyFrame_unique.Rd
- man/nanoarrow.Rd
- src/rust/src/lazy/dataframe.rs
- tests/testthat/test-dataframe.R
- tests/testthat/test-lazy.R
See https://github.com/pola-rs/r-polars/commit/08ce8c45c2a903e375ae0d344e0065e36ee4f2b0#r117064940
> Revert commits pushed to the main branch by accident

- DESCRIPTION
- NEWS.md
- R/dataframe__frame.R
- R/extendr-wrappers.R
- R/lazyframe__lazy.R
- man/DataFrame_unique.Rd
- man/LazyFrame_unique.Rd
- src/rust/src/lazy/dataframe.rs
- src/rust/src/utils/mod.rs
- tests/testthat/test-dataframe.R
- tests/testthat/test-lazy.R
> Add arg `maintain_order` to `unique()`

- .github/workflows/release.yaml
fix release pipeline misses devtools and fails
> fix release pipeline misses devtools

- NEWS.md
- R/expr__expr.R
- man/DataFrame_glimpse.Rd
- man/Expr_over.Rd
- tests/testthat/test-expr.R
Close #282. New behavior:
``` r
test <- pl$DataFrame(mtcars)
test$with_columns(
pl$col("mpg")$mean()$over(c("cyl", "drat"))
)
#> shape: (32, 11)
#> ┌──────┬─────┬───────┬───────┬───┬─────┬─────┬──────┬──────┐
#> │ mpg  ┆ cyl ┆ disp  ┆ hp    ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
#> │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
#> │ f64  ┆ f64 ┆ f64   ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
#> ╞══════╪═════╪═══════╪═══════╪═══╪═════╪═════╪══════╪══════╡
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 22.8 ┆ 4.0 ┆ 108.0 ┆ 93.0  ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 1.0  │
#> │ 21.4 ┆ 6.0 ┆ 258.0 ┆ 110.0 ┆ … ┆ 1.0 ┆ 0.0 ┆ 3.0  ┆ 1.0  │
#> │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …   ┆ …   ┆ …    ┆ … …
```
> Accept vector of colnames in `$over()`

- NEWS.md
- R/expr__expr.R
- R/expr__list.R
- R/extendr-wrappers.R
- R/series__series.R
- man/Expr_arg_sort.Rd
- man/Expr_rank.Rd
- man/Expr_set_sorted.Rd
- man/Expr_sort.Rd
- man/Expr_sort_by.Rd
- man/Series_is_sorted.Rd
- man/Series_set_sorted.Rd
- man/Series_sort.Rd
- man/arr_sort.Rd
- tests/testthat/test-expr.R
- tests/testthat/test-expr_arr.R
- tests/testthat/test-series.R
> Replace `reverse` by `descending` in sorting functions

- .Rbuildignore
- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- src/Makevars
- src/Makevars.win
Close #29
If not `NOT_CRAN=true`, set `CARGO_HOME` to a temporary directory to suppress writing to the home directory.
ref: extendr/rextendr#233
> fix(installation): set `CARGO_HOME` to a temp dir if not `NOT_CRAN=true`

- NEWS.md
- src/rust/src/lazy/dsl.rs
- src/rust/src/series.rs
> fix: reverse -> descending

- NEWS.md
Cf #296
@eitsupi nothing to do with symbols, just not enough indentation
> Fix news indentation

- src/rust/Cargo.lock
- src/rust/Cargo.toml
Fix #315
ref extendr/extendr#581
> fix: use libR-sys 0.4.0

- LICENSE.note
- src/rust/Cargo.lock
Follow up #317
#317 hasn't update the lock file.
> chore: cargo update

- src/Makevars
- src/Makevars.win
> build: always NOT_CRAN=true

- R/lazyframe__lazy.R
I forgot to push the changes in the R file in #358, no need to re-doc, I pushed the modified Rd files in the linked PR
> Minor error

- DESCRIPTION
- NEWS.md
@etiennebacher  I think we have it all now for 0.8.0 release
@eitsupi  I'm always unsure on correct of order releasing. Is this correct?
- Make release_0.8.0 branch, Done.
- use_this::use_version("minor") (0.8.0) + commit, Done
- Then click on release tap and create a release with release notes,[ release here](https://github.com/pola-rs/r-polars/releases/tag/v0.8.0rc) , Done
- use_this::use_version("dev") (0.8.0.9000) + commit
- merge release_0.8.0 via this PR
Close #364
> release 0.8.0

- R/expr__string.R
- man/ExprStr_splitn.Rd
> Fix docs of `splitn()`

- docs/mkdocs.orig.yml
> Add vignette "performance" in list of articles

- R/datatype.R
- man/pl_List.Rd
- man/pl_Struct_datatype.Rd
Allow `pl$List()` and `pl$Struct()`
Discovered in #397
> Allow `pl$List()` and `pl$Struct()`

- DESCRIPTION
Same as #307
The current excellent documentation (website) and many recent feature additions are a credit to @etiennebacher, which currently has the second highest number of commits.
> chore: make Etienne as co-author

- docs/docs/reference_home.Rmd
- docs/docs/stylesheets/extra.css
- vignettes/polars.Rmd
Mostly changes the navbar color and make the dark theme slightly less dark
**Before:**
**After:**
**Before:**
**After:**
> docs: increase font size for code

- .Rbuildignore
- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release-lib.yaml
- .github/workflows/release.yaml
- DESCRIPTION
- Makefile
- configure
- dev/generate-lib-sums.R
- tools/lib-sums.tsv
- tools/prep-lib.R
Close #408
Allows us to download binaries from GitHub Releases and skip the `cargo build` step using the mechanism copied from `prqlr`.
Like this:
```r
> Sys.setenv(NOT_CRAN="true")
> remotes::install_github("pola-rs/r-polars#450")
Downloading GitHub repo pola-rs/r-polars@bin-lib-install
Running `R CMD build`...
* checking for file ‘/tmp/Rtmpghk68j/remotes3e78001b4b/pola-rs-r-polars-9ece233/DESCRIPTION’ ... OK
* preparing ‘polars’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘polars_0.8.1.9000.tar.gz’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘polars’ ... …
```
> feat: allow "R source package with Rust library binary" installation

- .gitignore
- configure
> fix(installation): fix detecting r-universe logic

- R/dataframe__frame.R
- R/lazyframe__lazy.R
- man/DataFrame_explode.Rd
- man/LazyFrame_explode.Rd
> Fix docs for `DataFrame$explode()` and `LazyFrame$explode()`

- R/csv.R
- R/error_conversion.R
- R/json.R
- R/lazyframe__lazy.R
- R/utils.R
- tests/testthat/test-csv-read.R
- tests/testthat/test-enable_string_cache.R
- tests/testthat/test-joins.R
- tests/testthat/test-json_read.R
- tests/testthat/test-robj_to_rchoice.R
- vignettes/polars.Rmd
I have ran:
```sh
touch R/translation.R
GIT_DIF_TARGET=v0.9.0 make fmt-r
```
> refactor: auto formatting R files

- DESCRIPTION
- NEWS.md
- R/extendr-wrappers.R
> release: 0.10.0

- DESCRIPTION
- NEWS.md
> release: 0.10.1

- .github/workflows/docs.yaml
> ci(website): fix workflow

- DESCRIPTION
Related to #605 
This should fix the formatting problem, not the absence of vignettes
> Fix formatting issue due to latest `altdoc`

- altdoc/preamble_man_qmd.yml
- altdoc/preamble_vignettes_qmd.yml
- altdoc/preamble_vignettes_rmd.yml
- altdoc/stylesheets/extra.css
> Style docs output

- README.Rmd
- README.md
> Reorganize README

- README.Rmd
> Remove html preview from README

- altdoc/altdoc_postprocessing.R
> docs(website): better "Usage" section for IO

- README.md
- altdoc/mkdocs_static.yml
- vignettes/install.Rmd
Part of #485
After merging this, I will remove installation descriptions from the README in the follow-up PR.
> docs: add installation vignette

- man/ExprStr_contains_any.Rd
- man/ExprStr_replace_many.Rd
- man/ExprStr_reverse.Rd
> chore: regen docs

- altdoc/altdoc_postprocessing.R
> docs(website): better "usage" section for expressions in subnamespaces

- README.Rmd
- README.md
I don't know how this broken link was overlooked for so long.
> docs(readme): fix the link to the website

- DEVELOPMENT.md
I added this because I noticed that there is no documentation regarding how to update the toolchain version.
> docs(development): add note about rust-polars update and build the website locally

- altdoc/altdoc_postprocessing.R
> docs(website): fix escaping of angle brackets

- R/expr__categorical.R
- R/expr__expr.R
- R/expr__string.R
- R/functions__lazy.R
- R/lazyframe__lazy.R
- R/series__series.R
- man/ExprCat_set_ordering.Rd
- man/ExprStr_split_exact.Rd
- man/ExprStr_splitn.Rd
- man/Expr_repeat_by.Rd
- man/pl_all.Rd
* Remove some outdated `TODO`
* Better examples
NOTE: the R CMD failure is fixed in #689
> Clean some `TODO`

- .github/workflows/check.yaml
- Remove unnecessary steps and comments
- Add a step to upload bin lib (It's useful to be able to try test builds right away. https://github.com/pola-rs/r-polars/issues/725#issuecomment-1902685297)
> ci: clean up R CMD check GHA workflow

- DEVELOPMENT.md
- man/nanoarrow.Rd
- man/pl_from_epoch.Rd
A follow up for https://github.com/pola-rs/r-polars/pull/726#discussion_r1462740637
> docs: regen Rd file and add a note about S3 method documentation

- R/polars_envvars.R
https://github.com/pola-rs/r-polars/pull/735#discussion_r1468723961
> fix: print `threadpool_size()` as `POLARS_MAX_THREADS` in `polars_envvars()`

- Taskfile.yml
- man/polars-package.Rd
> docs: regen the package document

- R/dataframe__frame.R
- R/lazyframe__lazy.R
- R/series__series.R
- man/DataFrame_clone.Rd
- man/LazyFrame_clone.Rd
- man/Series_clone.Rd
- tests/testthat/test-dataframe.R
- tests/testthat/test-lazy.R
- tests/testthat/test-series.R
> docs: fix examples for `$clone()`

- NEWS.md
Completely missed this in #758
> docs: put `$write_parquet` in correct NEWS section

- NEWS.md
- R/dotdotdot.R
- tests/testthat/test-dataframe.R
- tests/testthat/test-expr_list.R
> Make it easier to create a DataFrame with a single list-column

- NEWS.md
Followup of #790, thanks for the reminder @eitsupi
> Bump news for `arr` subnamespace

- NEWS.md
Addresses https://github.com/pola-rs/r-polars/pull/800#discussion_r1485615687
> docs(news): more notes about feature flag changes

- .github/dependabot.yaml
> ci: fix the path of the action directory

- tests/testthat/_snaps/as_polars.md
- tests/testthat/test-as_polars.R
> test: `pl$DataFrame` can include vctrs_rcrd class vector

- Taskfile.yml
> dev: use `uv` for install python packages

- vignettes/install.Rmd
- vignettes/polars.Rmd
- Fix title
- Use `$method_name()` to method names
- Use `$fetch()` instead of `$limit()` (related to #840)
- Use `as.vector()` instead of `$to_vector()`
> docs(vignette): tweak vignettes

- NEWS.md
- R/dataframe__frame.R
- R/group_by.R
- R/lazyframe__lazy.R
- man/DataFrame_group_by.Rd
- man/LazyFrame_group_by.Rd
- src/rust/src/lazy/dataframe.rs
- tests/testthat/test-groupby.R
> feat: support named arguments in `$group_by()`

- DESCRIPTION
> Bump `altdoc` version

- R/expr__expr.R
- R/expr__list.R
- R/expr__name.R
- R/functions__lazy.R
- man/ExprList_diff.Rd
- man/Expr_quantile.Rd
- man/Expr_search_sorted.Rd
- man/pl_all.Rd
> chore: remove more outdated TODOs

- DESCRIPTION
> chore: bump rustc to nightly-2024-02-23

- R/dataframe__frame.R
- tests/testthat/test-dataframe.R
> refactor: simplify the schema only case of `pl$DataFrame()`

- .ecrc
- NEWS.md
> chore: fix editorconfig checker settings

- R/lazyframe__lazy.R
https://github.com/pola-rs/r-polars/pull/928#discussion_r1530378484
> fix: fix the assigning

- NEWS.md
This fixes the linter error on CI.
> docs(news): auto formatting

- .github/actions/setup/action.yaml
- .vscode/settings.json
Fix the comma and indent issues.
> chore: makes linter happy

- .github/workflows/mega-linter.yaml
- altdoc/mkdocs_static.yml
> chore: make linter happy

- NEWS.md
If this new line is missing, it does not seem to render correctly.
> docs(news): add blank line for mkdocs

- NEWS.md
- R/expr__expr.R
- man/Expr_over.Rd
- tests/testthat/test-expr_expr.R
Followup of #984 
I didn't add test and docs for `mapping_strategy = "explode"` since it's also not clear in python docs (esp. regarding the sorting requirement): https://github.com/pola-rs/polars/issues/15346
> Test and document `mapping_strategy` in `$over()` 

- tests/testthat/test-groupby.R
Close #797. Thanks for clearing that up @eitsupi
> Test for `agg()` with list literal

- altdoc/mkdocs_static.yml
https://github.com/pola-rs/r-polars/pull/1014#issuecomment-2050158236
> Add vignette on differences with Python in mkdocs yaml

- NEWS.md
- R/dataframe__frame.R
- R/lazyframe__lazy.R
- man/IO_sink_csv.Rd
- man/IO_sink_ipc.Rd
- man/IO_sink_ndjson.Rd
- man/IO_sink_parquet.Rd
- man/IO_write_csv.Rd
- man/IO_write_ipc.Rd
- man/IO_write_json.Rd
- man/IO_write_ndjson.Rd
- man/IO_write_parquet.Rd
- tests/testthat/test-csv-write.R
- tests/testthat/test-ipc.R
- tests/testthat/test-json_write.R
- tests/testthat/test-parquet.R
- tests/testthat/test-sink_stream.R
Close #1031.
@eitsupi I'm fine with releasing 0.16 after this one
> `$sink_*()` and `$write_*()` functions invisibly return the input

- DESCRIPTION
- NEWS.md
I would like to create a release to reflect the website URL change to R-universe.
> release: 0.16.3

- NEWS.md
- R/series__series.R
- man/pl_Series.Rd
- tests/testthat/test-series.R
Close #903
Also add the missing `strict` argument.
> fix!: change the argument order of `pl$Series()` to match to other languages

- NEWS.md
> docs: fix typo

- tests/testthat/test-expr_expr.R
- tests/testthat/test-groupby.R
- tests/testthat/test-lazy.R
> test: `$set_sorted()` is no longer needed for some context

- tests/testthat/test-ipc.R
> test: add a test case for the memory_map option

- tests/testthat/test-ipc.R
> test: skip overwriting test on windows

- NEWS.md
- R/dataframe__frame.R
- man/DataFrame_n_chunks.Rd
- tests/testthat/test-concat.R
- tests/testthat/test-dataframe.R
> Change default value for `strategy` in `$n_chunks()`

- R/expr__expr.R
- man/Expr_rolling_max.Rd
- man/Expr_rolling_mean.Rd
- man/Expr_rolling_median.Rd
- man/Expr_rolling_min.Rd
- man/Expr_rolling_quantile.Rd
- man/Expr_rolling_skew.Rd
- man/Expr_rolling_std.Rd
- man/Expr_rolling_sum.Rd
- man/Expr_rolling_var.Rd
> docs: adjust arg `window_size` for `$rolling_*()` functions

- DESCRIPTION
- NEWS.md
- tools/lib-sums.tsv
> release: version 0.18.0

- DESCRIPTION
- src/rust/src/lazy/dataframe.rs
> fix: should not use `unwrap()` in `RPolarsLazyFrame.cast`

- R/pkg-knitr.R
- tests/testthat/_snaps/pkg-knitr.md
- tests/testthat/test-pkg-knitr.R
> feat: use `_` as big mark (thousand-separator) of shape as like Python Polars

- R/after-wrappers.R
- R/as_polars.R
- R/error__trait.R
- R/expr__expr.R
- R/functions__lazy.R
- R/parse_as_duration.R
- R/series__series.R
Those will be fixed in the rewrite anyway
> chore: remove old TODOs

- .github/workflows/check.yaml
- .github/workflows/release-lib.yaml
- .github/workflows/release.yaml
> ci: replace macos-12 to macos-13

- man/DataFrame_class.Rd
- man/DataFrame_to_data_frame.Rd
- man/DataFrame_to_list.Rd
- man/LazyFrame_class.Rd
- man/S3_as.data.frame.Rd
- man/S3_as.vector.Rd
- man/Series_class.Rd
- man/Series_to_r.Rd
I did not build the R package locally in #1337 :)
> docs: regen Rd files

- altdoc/mkdocs.yml
> docs: Remove broken tab "About" on website

- NEWS.md
- R/dataframe-frame.R
- R/lazyframe-frame.R
- R/utils-deprecation.R
- man/dataframe__drop.Rd
- man/dataframe__drop_nans.Rd
- man/dataframe__drop_nulls.Rd
- man/dataframe__explode.Rd
- man/dataframe__partition_by.Rd
- man/dataframe__to_dummies.Rd
- man/dataframe__unique.Rd
- man/dataframe__unnest.Rd
- man/lazyframe__drop.Rd
- man/lazyframe__drop_nans.Rd
- man/lazyframe__drop_nulls.Rd
- man/lazyframe__explode.Rd
- man/lazyframe__unique.Rd
- man/lazyframe__unnest.Rd
- tests/testthat/_snaps/lazyframe-frame.md
- tests/testthat/test-lazyframe-frame.R
> fix: Allow dynamic dots in `<lazyframe>$unique` and `<dataframe>$unique`

- R/utils-parse-expr.R
> perf: Speed up when all selectors in dots are strings

- NEWS.md
- R/000-wrappers.R
- R/expr-expr.R
- src/rust/Cargo.lock
- src/rust/Cargo.toml
- src/rust/src/expr/general.rs
- tests/testthat/test-expr-expr.R
https://github.com/pola-rs/polars/releases/tag/py-1.33.0-beta.1
Turns out this also fixes #1522
> chore: Bump polars to prerelease version of py-1.33.0

- .github/workflows/release-lib.yml
- DESCRIPTION
- src/rust/Cargo.lock
- src/rust/Cargo.toml
Updated workflow to accommodate the new immutable release feature and lib updates accordingly.
> chore: Update rust lib and release workflow

- .github/workflows/build-docs.yml
- .github/workflows/test-r.yml
More space seem needed (Ref: #1542).
> ci(build-docs,test-r): More space on Linux runner

- .github/workflows/release-lib.yml
It works : https://github.com/pola-rs/r-polars/actions/runs/17708198804
> ci(release-lib): Fix release lib workflow to create tags

- NEWS.md
- R/output-batches.R
- R/output-csv.R
- R/output-ipc.R
- R/output-json.R
- R/output-parquet.R
- man/dataframe__write_ipc.Rd
- man/lazyframe__sink_batches.Rd
- man/lazyframe__sink_csv.Rd
- man/lazyframe__sink_ipc.Rd
- man/lazyframe__sink_ndjson.Rd
- man/lazyframe__sink_parquet.Rd
- tests/testthat/_snaps/output-batches.md
- tests/testthat/_snaps/output-csv.md
- tests/testthat/_snaps/output-ipc.md
- tests/testthat/_snaps/output-json.md
- tests/testthat/_snaps/output-parquet.md
- tests/testthat/test-output-batches.R
- tests/testthat/test-output-csv.R
- tests/testthat/test-output-ipc.R
- tests/testthat/test-output-json.R
- tests/testthat/test-output-parquet.R
> feat: `lazy_sink_*` methods and support the `engine` argument for `sink_*` methods

- R/output-batches.R
- man/lazyframe__sink_batches.Rd
> docs: Improve examples of `<lazyframe>$sink_batches()`

- R/interchange-protocol.R
- R/output-ipc.R
- R/series-s3-nanoarrow.R
- man/dataframe__write_ipc.Rd
- man/dataframe__write_ipc_stream.Rd
- man/lazyframe__sink_ipc.Rd
- man/pl.Rd
- man/s3-as_nanoarrow_array_stream.Rd
- tests/testthat/_snaps/interchange-protocol.md
- tests/testthat/test-interchange-protocol.R
> feat: Implement `pl$CompatLevel` to call newest or oldest compat level
