pola-rs/r-polars

.Rbuildignore, DESCRIPTION, LICENSE.md
Fix this NOTE.
```
❯ checking DESCRIPTION meta-information ... NOTE
Malformed Title field: should not end in a period.
Non-standard license specification:
use_mit_license()
Standardizable: FALSE
```
=> usethis::use_mit_license()

src/Makevars.win
We found touching it is enough to deceive the compiler (ref: https://github.com/extendr/rextendr/issues/209#issuecomment-1328236139).
=> Touch libgcc_eh.a

src/Makevars, src/Makevars.win
Remove lines that are not considered to be working and formatting.
Since a new shell is executed for each line in Make, there is no point in changing directories with non-consecutive commands in a target, I think.
```sh
$ cat <<"EOF" >/tmp/Makefile
all:
echo $(PWD)
cd /tmp/
echo $(PWD)
EOF
$ make -f /tmp/Makefile
echo /
/
cd /tmp/
echo /
/
```
=> Refactor Makefiles

DESCRIPTION
=> chore: install nanoarrow from cran

DESCRIPTION
r-univese cannot find nanoarrow on github, try push the commit to runiverse
https://github.com/r-universe/rpolars/actions/runs/4392816596/jobs/7692815192#step:3:512
=> chore: install nanoarrow from cran (#72)

DESCRIPTION
Some auto generated citation snippets from this polars package display me as the sole author of polars, which is not right.
I have added Ritchie as first author.
btw "cre" means package maintainer
[I skimmed this guide](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf)
Any suggestions on how to depict authorship should freely be debated among the contributors. I have no strong opinions on this.
=> credit Ritchie as author

R/csv.R
1-line commit to ensure that `pl$lazy_csv_reader` and friends expand paths.
``` r
write.csv(airquality, "~/Downloads/air.csv")
pl$csv_reader("~/Downloads/air.csv")
```
=> Expand `path` in `pl$lazy_csv_reader`

R/s3_methods.R, tests/testthat/test-s3_methods.R
#146
The only S3 methods which now call collect are `as.data.frame()` and `as.matrix()`. In those cases, the user makes an explicit choice to bring everything in memory as R objects, so it seems fine to me.
In all other cases, an informative error is raised.
=> Issue Some methods execute `LazyFrame$collect()` #146

inst/misc/Makevars_symlinking, src/Makevars, src/Makevars.win, src/rust/Cargo.lock, src/rust/Cargo.toml
Related to #149
Rename the internal Rust crate from `polars` to `r-polars` for clarity.
=> chore: rename the crate and lib to r-polars

DESCRIPTION, NEWS.md
I checked with github autogen and it seems all PR's are mentioned in NEWS except, PR's updating the news it self (#108, #118) and a refactor of internal conversion (`robj_to!(u8, ...)` #115 ) which I guess should be omitted.
=> bump polars to 0.6.0

README.Rmd, README.md
Installation of binaries from r-universe now prefers a '4.3' path for the current R release.
=> R 4.2 -> 4.3 for r-universe binaries

README.Rmd, README.md
Close #189. 
@sorhawell before merging, do we highlight `maintain_order` somewhere in the docs? (cf suggestion in #189)
=> Use `maintain_order = TRUE` in README

Makefile
make requirements-r calls
`pak::local_install_deps(dependencies = c("all", "Config/Needs/dev", "Config/Needs/website"))`
however `upgrade=TRUE` will implicitly try compile any +100 dev dependencies of CRAN does not have the binary yet. This is a problem on a macbook because various packages do not easily compile on any version, e.g. take httpuv where best fix is not manually modify makevars file.
https://github.com/rstudio/httpuv/issues/325
I suggest setting upgrade = FALSE. This will not only prefer binaries, but also only upgrade if strictly required (which is not ideal I guess). It seems pak provides no middle ground like, "prefer latest binary for any package".
If a better solution exists, we should just ditch this PR.
=> pak::local_install_deps(upgrade = FALSE) for ensure binary install

flake.nix
Allow `builtinsFetchGit` in the cargoDeps attribute. This allows the `package` and `devShells` to keep building, without needing to update the `outputHashes` manually.
~Potentially supercedes: #227~
Fixes: #226
=> build(nix): allow  builtinsFetchGit

DESCRIPTION, Makefile, tests/testthat/_snaps/knitr.md
Minor changes to address the following three recently CRAN released packages.
- altdoc
- knitr
- rextendr
Currently the test is broken by the new version of knitr, so this PR needs to be merged.
=> chore: bump dev packages and fix test

.github/workflows/docs.yaml
Any fork having a branch called main will currently try to deploy docs without the DEPLOY_DOCS key and fail.
That is annoying for any external developer.
This PR aborts deploying docs if not DEPLOY_DOCS key are actively stored in fork repo.
=> disable docs deployment if not DEPLOY_DOCS key is present in github SECRETS

NEWS.md, R/dataframe__frame.R, R/expr__expr.R, man/DataFrame_select.Rd, tests/testthat/test-dataframe.R, tests/testthat/test-lazy.R
Related to #259 (I couldn't deprecate `construct_ProtoExprArray` though so no problem to close this PR if you want to do it all at once in another PR).
New behaviour:
``` r
l_expr = list(
pl$col("a"),
pl$col("b")
)
pl$DataFrame(a = 1:3, b = 1:3, c = 1:3)$select(l_expr)
#> shape: (3, 2)
#> ┌─────┬─────┐
#> │ a   ┆ b   │
#> │ --- ┆ --- │
#> │ i32 ┆ i32 │
#> ╞═════╪═════╡
#> │ 1   ┆ 1   │
#> │ 2   ┆ 2   │
#> │ 3   ┆ 3   │
#> └─────┴─────┘
pl$DataFrame(a = 1:3, b = 1:3, c = 1:3)$select(l_expr, "c")
#> shape: (3, 3)
#> ┌─────┬─────┬─────┐
#> │ a   ┆ b   ┆ c   │
#> │ --- ┆ --- ┆ --- │
#> │ i32 ┆ i32 ┆ i32 │
#> ╞═════╪═════╪═════╡
#> │ 1   ┆ 1   ┆ 1   │
#> │ 2   ┆ 2   ┆ 2   │
#> │ 3   ┆ 3   ┆ 3   │
#> └─────┴─────┴─────┘
```
=> Accept lists in `select()`

.github/workflows/check.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml, NEWS.md, src/Makevars, src/Makevars.win, src/rust/Cargo.toml
Related to #80 and #90
Enable/disable `simd` by environment variable at build time.
`simd` is disabled by default for CRAN releases.
=> feat!: add `simd` feature and remove `polars/simd` from the default feature

R/extendr-wrappers.R, src/rust/src/rlib.rs, tests/testthat/test-extendr.R
=> test extendr rprintln supports `%`-char

NEWS.md, src/rust/src/info.rs
https://github.com/pola-rs/r-polars/pull/271#issuecomment-1614721193
We should use `feature` here, not `target_feature`.
Now it works fine.
```r
> polars_info()
R Polars package version: 0.6.1.9000
Features:         
simd TRUE
```
=> fix: `polars_info()` shows features correctly

NEWS.md, R/extendr-wrappers.R
Includes a fix to undo extendr-wrappers changes that was incorrectly updated by #268.
=> docs(NEWS): polish NEWS

DESCRIPTION, R/expr__expr.R, man/Expr_class.Rd
https://github.com/pola-rs/r-polars/issues/80#issuecomment-1617317605
=> chore(docs): updates for R check notes

DESCRIPTION
Cf #298 
@eitsupi is this enough to use the dev version of `altdoc`?
=> Use `altdoc` dev version

.github/workflows/docs.yaml, LICENSE.note, Makefile
Sorry, I forgot that we needed to add this before submitting to CRAN.
Since CRAN policy instructs us to put the license regarding the source code included in the binary in the LICENSE.note, so adds that via the `rextendr`'s function and `cargo-license`.
See extendr/rextendr#236 for details about LICENSE.note.
=> docs: add LICENSE.note about Rust dependencies

DESCRIPTION, NEWS.md, README.Rmd, README.md
=> docs: can't install from CRAN now

README.Rmd, README.md
Hi, thanks for making this great package! While testing local build, I noticed I had to adapt the command for the local build. Hence this mini PR. Cheers, Philipp
=> fix local build CMD

DESCRIPTION, R/extendr-wrappers.R, man/nanoarrow.Rd, src/rust/src/rlib.rs, tests/testthat/test-extendr-meta.R
adds this internal function and use [to check polars cloning behavior here ](https://github.com/etiennebacher/tidypolars/pull/22)
```rust
#[extendr] //could be used to check copying/cloning behavior of R objects
pub fn clone_robj(robj: Robj) -> Robj {
robj.clone()
}
```
=> Add robj clone

DESCRIPTION, NEWS.md, R/extendr-wrappers.R, man/pl_corr.Rd, man/pl_cov.Rd, man/pl_rolling_corr.Rd, man/pl_rolling_cov.Rd, src/rust/src/rlib.rs, src/rust/src/utils/mod.rs, tests/testthat/test-without_library_polars.R
=> fix use polars without library(polars)

R/lazyframe__lazy.R, R/rust_result.R, man/LazyFrame_collect_in_background.Rd, tests/testthat/test-rbackground.R
`collect(collect_in_background = TRUE)`  referred to old removed implementation.
fix + unit test + style some `<-`
no news because bug was introduced in this 9000 version and has not been released
=> fix collect(collect_in_background=TRUE)

R/info.R, man/nanoarrow.Rd, tests/testthat/_snaps/info.md, tests/testthat/test-info.R
this is an R side implementation. A rust side implementation will likely be available from rust-polars 0.31.0
https://github.com/pola-rs/polars/pull/9660
This partially resolves: https://github.com/pola-rs/r-polars/issues/288
=> Add rust polars version info

.github/workflows/release.yaml, src/Makevars, src/Makevars.win
=> ci: fix release workflow to enable full features of Linux arm64 packages on GitHub releases

.github/workflows/release-lib.yaml, src/rust/Cargo.lock, src/rust/Cargo.toml
Part of #408
This PR adds a new workflow to upload binary libraries to GitHub releases.
These binaries will be used "R source package with Rust library binary" installation.
Copied from <https://github.com/eitsupi/prqlr/blob/97cc6522adc7ea3c9d7273a67737e226ab6b597a/.github/workflows/release-lib.yml>
After this is merged, I will update our existing release workflow to not do Rust builds by rewriting it.
(We should have done a library release before doing the release, so we can use that binary libraries to build the R binary package)
=> ci: add release-lib workflow to upload binary libraries to GitHub releases

R/csv.R, R/parquet.R
This PR fixes the error `Error in eval(expr, p) : object 'pl' not found` when execute the read functions e.g. `polars::pl$read_csv(path)`.
=> fix: fix read_* functions when the package is not loaded

vignettes/polars.Rmd
Related to https://github.com/pola-rs/r-polars/issues/404#issuecomment-1789261637
Thanks for the info @grantmcdermott
=> Update vignette section on scanning partitions

tests/testthat/test-dataframe.R, tests/testthat/test-lazy.R
For the behavior of `$explode()` on character columns, that might change.
Following https://github.com/pola-rs/r-polars/pull/464#issuecomment-1793191297
=> Add test for `DataFrame$explode()` and `LazyFrame$explode()`

R/csv.R, R/extendr-wrappers.R, R/json.R, src/rust/src/rdataframe/read_csv.rs, tests/testthat/test-csv-read.R, tests/testthat/test-json_read.R
=> Refactor again CSV reading

DESCRIPTION, Makefile, README.Rmd, README.md
I want to create a vignette about the installation and this PR is needed for to get the toolchain version from within the package.
=> refactor: record the rust toolchain version to the DESCRIPTION file

.github/actions/setup/action.yaml, .github/workflows/check.yaml, .github/workflows/release.yaml
Recent versions of `pak` install system dependencies by default, so setting `CI: false` was meaningless. (See r-lib/rig#184)
And, installing system dependencies by pak does not seem to cause any harm, so we can leave the default settings to simplify configuration.
=> ci: use pak's sys reqs installation

docs/docs/stylesheets/extra.css
Currently, code appears too big in some places, such as argument description:
=> Minor styling

LICENSE, LICENSE.md
Hi all,
I was reviewing the repositories in the Polars organization for license files. I found that the open source license in this repo is non-standard:
`LICENSE` containing only copyright - but no full name included
`LICENSE.md` with an MIT license, again with no name included.
I set the year to 2022 (year of the first commit) and the name to the original author @sorhawell . Of course there have been excellent contributions by many authors since then, but I believe this is the correct way to go about it with regards to licensing. Though I am not sure (not a lawyer). 
The `LICENSE` file is automatically picked up by GitHub. I am not sure the Markdown file is needed, but I don't want to break anything so I left it intact.
=> Update LICENSE file

LICENSE, LICENSE.md
Reverts #489
Including the full text of the MIT License in the LICENSE file is not allowed by CRAN.
<https://cran.r-project.org/doc/manuals/r-release/R-exts.html> says:
> One of the “standard” short specifications
> 
> GPL-2 GPL-3 LGPL-2 LGPL-2.1 LGPL-3 AGPL-3 Artistic-2.0
> BSD_2_clause BSD_3_clause MIT
> Whereas you should feel free to include a license file in your source distribution, please do not arrange to install yet another copy of the GNU COPYING or COPYING.LIB files but refer to the copies on https://www.r-project.org/Licenses/ and included in the R distribution (in directory share/licenses). Since files named LICENSE or LICENCE will be installed, do not use these names for standard license files. To include comments about the licensing rather than the body of a license, use a …
=> Revert "Update LICENSE file"

src/rust/src/utils/mod.rs
=> fix: ensure `polars::` when call R `pl` in Rust

NEWS.md, R/s3_methods.R, man/S3_extract.Rd, tests/testthat/test-s3_methods.R
For base data.frame, it is possible to filter on columns that are not included in the result, such as `mtcars[mtcars$cyl >= 8, c("disp", "mpg")]`, but until now this was not possible with polars DataFrame because column selection was performed first.
This PR fixes this behavior by filtering first and also allows filtering by Expr for LazyFrame.
=> fix: The Extract function should filter rows before selecting columns

DESCRIPTION
We have been using the edge version of `testthat` since https://github.com/pola-rs/r-polars/pull/455#discussion_r1380464052, but `testthat` 3.2.1 is now on CRAN.
So we can switch to that.
=> test: switch to use the new release version of `testthat`

DESCRIPTION, R/Field.R, R/after-wrappers.R, R/expr__datetime.R, R/expr__expr.R, R/expr__list.R, R/extendr-wrappers.R, R/functions__lazy.R, R/parquet.R, R/rust_result.R, R/series__series.R, altdoc/altdoc_preprocessing.R, dev/styler_utils.R, inst/misc/develop_polars.R, inst/misc/examples/from_arrow.R, inst/misc/renv_mentions.R, inst/misc/simple_benchmark.R, tests/testthat/_snaps/knitr.md, tests/testthat/files/flights.Rmd, tests/testthat/test-arrow_extendr_polars.R, tests/testthat/test-context.R, tests/testthat/test-expr_arr.R, tests/testthat/test-expr_expr.R, tests/testthat/test-parquet.R, tests/testthat/test-s3_methods.R, tests/testthat/test-series.R
update to rpolars_style  to not convert  the `<<-`  operator to `=` in e.g. `utils.R`
=> rpolars_style 0.1.1: fix styler `<<-`   and style all files 

DESCRIPTION, Makefile
Related to #605 
From what I can see in https://github.com/rpolars/rpolars.github.io/tree/main/vignettes, vignettes are well rendered to markdown, but for some reason `mkdocs` doesn't build their HTML page. This PR uses a debugging branch in altdoc that prints the output of `mkdocs build`.
=> Fix vignette absence

.Rbuildignore, .gitignore, Taskfile.yml
A part of #556
Allows use of `task` instead of `make`.
Most of the content was copied from the prqlr repository.
=> build: add Taskfile.yml to use task as a build tool

R/error__rpolarserr.R, R/info.R
This includes reducing extraneous function calls and improving error messages.
Related to #241 (after this change, the `check_feature` function does not invoke Polars, so the number of threads can be changed after the `check_feature` function is called)
=> refactor: minor refactoring of the check_feature functon

.devcontainer/devcontainer.json
Replace #312.
Add a container definition to be able to work with GitHub Codespaces etc.
(I'm using this locally and it seems to be working fine.)
=> build: add devcontainer.json for to support Dev Containers

NEWS.md
Related to #631 and #632
At least a temp fix before the NEWS formatting is fixed in `altdoc`
=> docs: fix changelog formatting

R/utils.R
Close #281 
Error message is now identical when the code is run interactively and in `reprex()`:
``` r
pl$DataFrame(iris)$foo()
#> Error: syntax error: foo is not a method/attribute of the class RPolarsDataFrame 
#>  when calling method:
#>  pl$DataFrame(iris)$foo
```
<sup>Created on 2023-12-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
=> Fix error message in reprex

Taskfile.yml
I noticed that I can't use it with Codespaces because the devcontainer build stops if the `-y` option of `cargo binstall` is not set.
=> build: fix devcontainer updateContentCommand not to hang

dev/styler_utils.R
The first arg of `makePSOCKcluster` is `names`, not `spec`
=> fix: styler file fails on Windows

R/expr__datetime.R, man/ExprDT_cast_time_unit.Rd, man/ExprDT_combine.Rd, man/ExprDT_convert_time_zone.Rd, man/ExprDT_day.Rd, man/ExprDT_epoch.Rd, man/ExprDT_hour.Rd, man/ExprDT_iso_year.Rd, man/ExprDT_microsecond.Rd, man/ExprDT_millisecond.Rd, man/ExprDT_minute.Rd, man/ExprDT_month.Rd, man/ExprDT_nanosecond.Rd, man/ExprDT_offset_by.Rd, man/ExprDT_ordinal_day.Rd, man/ExprDT_quarter.Rd, man/ExprDT_replace_time_zone.Rd, man/ExprDT_round.Rd, man/ExprDT_second.Rd, man/ExprDT_strftime.Rd, man/ExprDT_timestamp.Rd, man/ExprDT_truncate.Rd, man/ExprDT_week.Rd, man/ExprDT_weekday.Rd, man/ExprDT_with_time_unit.Rd, man/ExprDT_year.Rd
Something forgotten in previous PRs. These were the last `@usage NULL` to remove
=> docs: remove `@usage NULL` for datetime methods

vignettes/install.Rmd
- pl$polars_info -> polars_info
- Add note about `MY_UNIVERSE`
- Other minor update
=> docs: minor updates for the install vignette

.github/workflows/docs.yaml
I noticed that #669 was not triggering the docs workflow due to a typo in this file.
=> ci: fix typo of the path in the ci trigger

configure, tools/prep-lib.R, vignettes/install.Rmd
Same as eitsupi/prqlr#247
R-universe started distributing R binary packages for arm64 macOS yesterday (r-universe-org/help#340).
This PR should enable both of the following two R package cross-compilation methods to work.
1. Compile from Rust source (confirmed with eitsupi/prqlr#247)
2. Download and use Rust binary libraries from the internet (Checked on my R-universe https://github.com/eitsupi/eitsupi.r-universe.dev/commit/2b5163fe86eac278eee3a1fe7a343b7c9bd37518)
=> feat(installation): support cross-compiling the R package via the `--host` option of the configure script

R/options.R, man/pl_options.Rd
- Rename the Rd file
- The documentation stated that named arguments were required, but this was not the case. This is corrected.
=> fix: rename pl$options' Rd file and enforce named arguments

DESCRIPTION, Taskfile.yml
Related to #700
This is required for automatic linking support via `downlit`, as `downlit` expects the very first URL in the URL field to be a pkgdown site.
``` r
downlit::autolink("polars::as_polars_df()")
#> [1] "<a href='https://rpolars.github.io/man/as_polars_df.html'>polars::as_polars_df()</a>"
```
<sup>Created on 2024-01-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
=> fix: set the API document site to the primary URL of package

DESCRIPTION, NEWS.md, R/lazyframe__lazy.R, src/rust/Cargo.toml, src/rust/src/lazy/dataframe.rs, tests/testthat/test-dataframe.R, tests/testthat/test-lazy.R, tools/lib-sums.tsv
Close #733 
Close #734 (which will be hard to replicate now that #733 is fixed)
=> fix: `$sort()` no longer panicks when `descending = NULL`

src/rust/Cargo.lock, src/rust/src/lazy/dataframe.rs, src/rust/src/lazy/dsl.rs, src/rust/src/rdatatype.rs, src/rust/src/utils/mod.rs
I think the `robj_to_` macros are now the way to go for converting R objects to anything, so I move some interpolation methods to use these macros
=> chore: refactor some rust code

R/extendr-wrappers.R, src/rust/src/arrow_interop/mod.rs, src/rust/src/arrow_interop/to_rust.rs, src/rust/src/rlib.rs
Part of #732
- Remove unused internal R function `rb_list_to_df`
- Move some codes from `to_rust.rs` to `mod.rs` for future use.
- Remove some unused Rust functions and comments.
=> refactor: remove unused functions related to arrow

.github/workflows/check.yaml, .github/workflows/release-lib.yaml, .github/workflows/release.yaml
Incorporate the newly available arm64 macOS runner into the CI.
It has been announced that `macos-latest` will be switched from `macos-12` (amd64) to `macos-14` (arm64) in a few months, so it has been changed to explicitly specify `macos-12` or `macos-14`.
=> ci: add `macos-14` (arm64 macOS) to GitHub Actions matrixes

altdoc/altdoc_preprocessing.R
We already had a section for `RollingGroupBy`, I think it makes sense to have one for `RollingGroupBy` too.
Before:
After:
=> docs(website): show DynamicGroupBy in a different section

.Rbuildignore, .lintr.R, inst/misc/develop_polars.R, tests/testthat/test-expr_expr.R, tests/testthat/test-sink_stream.R, tests/testthat/test-whenthen.R, vignettes/userguide.Rmd
Close #766
Part of #214
Note that this PR does not correct all warnings because there are too many to correct.
Also, because `lint_package` takes several minutes to run, the Taskfile does not run the function.
=> refactor: add the lintr config file and some refactoring

vignettes/polars.Rmd
I saw a user [on SNS](https://twitter.com/LegoAnand/status/1751190842641957042) who could not figure out how to convert RPolarsDataFrame to data.frame.
I would like to emphasize that it is easy to convert between objects by actively using S3 methods.
- Use `as_polars_*` functions instead of `pl$*` function to convert base objects to polars objects.
- Use `as.data.frame` instead of `$to_data_frame()`.
- Use `<DataFrame>$write_parquet` instead of `arrow::write_parquet`.
=> docs(vignette): update the introduction vignette to use the new functions

vignettes/polars.Rmd
Related to #779. I tested this locally and the vignette knits correctly if `arrow` is not installed
=> Render vignettes even if `arrow` is absent

NEWS.md, R/polars_info.R, man/polars_info.Rd, tests/testthat/_snaps/polars_info.md, tests/testthat/test-polars_info.R
Change to return a more appropriately hierarchical list.
And the display also be changed slightly.
=> refactor!: change the `polars_info()` output structure

R/dataframe__frame.R, R/lazyframe__lazy.R, R/polars_options.R, man/DataFrame_group_by.Rd, man/DataFrame_pivot.Rd, man/DataFrame_sort.Rd, man/DataFrame_unique.Rd, man/IO_sink_csv.Rd, man/IO_sink_ipc.Rd, man/IO_sink_ndjson.Rd, man/IO_sink_parquet.Rd, man/LazyFrame_group_by.Rd, man/LazyFrame_sort.Rd, man/LazyFrame_unique.Rd, man/polars_options.Rd
* For `group_by`, clarify that `maintain_order` only influences the order of groups, not the order of rows in each group
* Use a different definition for each type of function. `maintain_order` doesn't mean the same thing for `sink_*()` and for `unique()` for example
* Clarify that `polars_options()$maintain_order` only affects the value of `maintain_order` in `group_by` functions. We can discuss if this should be extended to all `maintain_order` args, but that's how it has been in the code so far.
Easier to review by looking at the content of the Rd files.
=> docs: clarify argument `maintain_order`

NEWS.md, R/expr__array.R, R/expr__string.R, R/polars_info.R, man/ExprArr_max.Rd, man/ExprArr_min.Rd, man/ExprStr_to_titlecase.Rd, man/polars_info.Rd, src/rust/Cargo.toml, src/rust/src/info.rs, src/rust/src/lazy/dsl.rs, tests/testthat/_snaps/polars_info.md, tests/testthat/test-expr_array.R, tests/testthat/test-expr_string.R, vignettes/install.Rmd
Close #300
Match with py-polars.
- `polars/nightly` includes `polars/simd`, and py-polars does not specify `polars/simd` directly but includes `polras/nightly` in the `nightly` feature.
- The `default` feature includes the `sql` feature (because `sql` no longer requires nightly toolchain).
=> refactor!: feature flags reorganizization

.github/dependabot.yaml
I did not know that additional configuration was required to have GitHub Actions check local actions.
> Dependabot will ignore actions or reusable workflows referenced locally (for example, `./.github/actions/foo.yml)`.
https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions
Also add settings for updating devcontainer.json.
=> ci: make dependabot to check local action and devcontainer config file

.github/workflows/check.yaml, .github/workflows/release-lib.yaml, .github/workflows/release.yaml
Artifacts with the same name are no longer allowed and must use unique names.
=> ci: migrate to actions/upload-artifact@v4 and actions/download-artifact@v4

NEWS.md, R/as_polars.R, R/construction.R, man/as_polars_df.Rd, tests/testthat/test-as_polars.R
Close #816
It used to call `pl$DataFrame` internally, but has been completely rewritten to not call it.
Speeds seem to be comparable, but memory usage may have been reduced.
(The `bench` package does not measure memory usage on the Rust side, but given that the output RPolarsDataFrame is the same, memory usage on the Rust side should not be much different.)
``` r
big_df = do.call(rbind, lapply(1:10, \(x) nycflights13::flights))
library(nanoarrow)
bench::mark(
pl_DataFrame = {
pl$DataFrame(big_df)
},
as_polars_df = {
as_polars_df(big_df)
},
from_nanoarrow = {
as_polars_df(as_nanoarrow_array_stream(big_df))
},
check = FALSE,
min_iterations = 10L
)
#> # A tibble: 3 × 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm> …
```
=> refactor: rewrite `as_polars_df.data.frame`

.github/workflows/release-lib.yaml
Sorry, the release job failed because the fixes were not sufficient.
See https://github.com/actions/download-artifact/blob/348754975ef0295bfa2c111cba996120cfdf8a5d/docs/MIGRATION.md
=> ci: fix migration to actions/download-artifact@v4

.github/actions/setup/action.yaml, .github/workflows/check.yaml, .github/workflows/docs.yaml, .github/workflows/release-lib.yaml, .github/workflows/release.yaml
Workflow started failing because R was not installed on the new macOS runner (actions/runner-images#9394).
I don't know if this is a temporary or permanent problem, but this PR will correct for the possibility of a temporary problem.
=> ci: ensure install R on macOS runner

.github/workflows/docs.yaml
Currently the binary for the new version of the `arrow` package is not yet available via P3M, so that is installed source from CRAN.
Switching to `r-lib/actions/setup-r-dependencies` should speed up the process.
=> ci(website): use `r-lib/actions/setup-r-dependencies` to cache R packages

DESCRIPTION, R/zzz.R, tests/testthat/test-dataframe.R, tests/testthat/test-expr_expr.R, tests/testthat/test-expr_list.R, tests/testthat/test-lazy.R, tests/testthat/test-melt.R
In fact, it is used only within the tests and there is little need to use it.
=> refactor: remove the `data.table` package from Suggests

.github/actions/setup/action.yaml
Fix #838
Same as pola-rs/polars#14715
I am not convinced that this will solve the problem, but I pray that following upstream will help.
=> ci: limit cmake threads to fix crash compiling `libz-ng-sys` on macos-14

NEWS.md, R/expr__list.R, R/expr__string.R, man/ExprList_eval.Rd, man/ExprStr_concat.Rd, tests/testthat/test-expr_string.R
=> fix!: change the default delimiter of `$str$concat` from `"-"` to `""` and `ignore_nulls` should be a named argument

NEWS.md, R/datatype.R, R/expr__expr.R, R/expr__string.R, man/DataType_Datetime.Rd, man/ExprStr_strptime.Rd, man/ExprStr_to_date.Rd, man/ExprStr_to_datetime.Rd, man/ExprStr_to_time.Rd, man/Expr_div.Rd, man/pl_dtypes.Rd, tests/testthat/test-expr_string.R
Fix #884
The documentation said the default was `NULL`, but in fact there was no default value and an error would occur if the user did not specify one.
In addition, documentation has been improved and tests for default parsable values have been added.
=> fix: the default value of `$str$strptime()`'s format

NEWS.md, R/series__series.R, man/pl_Series.Rd, tests/testthat/test-series.R
=> feat: more arguments of `pl$Series`

DESCRIPTION, NEWS.md, R/dataframe__frame.R, R/lazyframe__lazy.R, man/DataFrame_drop.Rd, man/LazyFrame_drop.Rd, tests/testthat/test-dataframe.R, tests/testthat/test-lazy.R
=> Change `$drop()` input from `columns` to `...`

R/dataframe__frame.R
Refactor in #904 considerably slowed down the `DataFrame` creation with `schema` only:
``` r
schema <- list()
for (i in 1:1000) {
schema[[paste0("var_", i)]] <- pl$Float64
}
bench::mark(
pre_904 = {
largs <- lapply(seq_along(schema), \(x) {
pl$lit(numeric(0))$cast(schema[[x]])$alias(names(schema)[x])
})
pl$select(largs)
}, 
post_904 = {
lapply(schema, \(dtype) pl$Series(NULL)$cast(dtype)) |>
pl$select()
}
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 pre_904    992.55ms 992.55ms     1.01     10.5MB     17.1
#> 2 post_904      2.99s    2.99s     0.335    14.7MB     10.4
```
=> Revert refactor of `pl$DataFrame()` with `schema` only

vignettes/polars.Rmd
Recently CI on macOS started failing. Probably because the binary of the arrow package on CRAN does not have the dataset feature enabled.
=> docs: skip the example if `arrow` package's dataset feature is not available

R/functions__lazy.R, man/pl_mean_horizontal.Rd
Following #959 
* Use `@inheritParams`
* Small changes in the examples:
* Remove useless string column
* Add some rows with `NaN` or `Inf` 
* Add an example with a literal value
=> Small improvements in docs of `pl$mean_horizontal()`

R/expr__string.R, man/ExprStr_split.Rd
Close #971 
Same behavior in R and Python:
``` r
pl$DataFrame(x = c("0:89 29442:2 2:2 1:5"))$with_columns(
foo=pl$col("x")$str$split(" *")
)
#> shape: (1, 2)
#> ┌──────────────────────┬──────────────────────────┐
#> │ x                    ┆ foo                      │
#> │ ---                  ┆ ---                      │
#> │ str                  ┆ list[str]                │
#> ╞══════════════════════╪══════════════════════════╡
#> │ 0:89 29442:2 2:2 1:5 ┆ ["0:89 29442:2 2:2 1:5"] │
#> └──────────────────────┴──────────────────────────┘
pl$Series("0:89 29442:2 2:2 1:5")$str$split(" *")
#> polars Series: shape: (1,)
#> Series: '' [list[str]]
#> [
#>  ["0:89 29442:2 2:2 1:5"]
#> ]
```
```python
import polars as pl
pl.DataFrame({"x": ["0:89 29442:2 2:2 1:5"]}).with_columns( …
```
=> docs: `$str$split()` doesn't use regexes

NEWS.md, src/rust/Cargo.lock, src/rust/Cargo.toml
See extendr/extendr#716 (Related to #929 and #993)
=> chore: update extendr-api to prevent crashing R session

NEWS.md, R/as_polars.R, R/series__series.R, man/as_polars_series.Rd, man/pl_Series.Rd
Related to #1012.
`as_polars_series.default()` used to call `pl$Series()`, but will be changed so that `pl$Series()` calls `as_polars_series()`.
This will ensure that every object is properly converted to a Series.
Python's `polars.Series.__init__()` internally converts various objects into a Series through a large number of conditional branches. This update is very similar to that.
=> refactor: swap `pl$Series` and `as_polars_series.default`

NEWS.md, R/construction.R, tests/testthat/test-as_polars.R
A follow up for #1021
I was trying more complex nested type cases and learned that the columns of list class of data.frame are `AsIs` class and the list class is hidden.
``` r
data.frame(a = I(list(data.frame(b = 1L))))$a |> class()
#> [1] "AsIs"
```
<sup>Created on 2024-04-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
So it was necessary to add a process here to convert this column back to the list class to convert it to the Series as intended.
=> fix!: fix list type column conversion from data frame

NEWS.md, R/as_polars.R, man/as_polars_series.Rd, src/rust/src/conversion_r_to_s.rs, tests/testthat/test-as_polars.R
A follow up for #1021
This change will allow for more proper conversion from lists that contain NULLs or empty lists.
For example, in 0.15.1, a strange error occurs in the following case:
```r
> as_polars_series(list(list(), list(1, 2)))
Error: Execution halted with the following contexts
0: In R: in pl$Series():
0: During function call [as_polars_series(list(list(), list(1, 2)))]
1: Encountered the following error in Rust-Polars:
data types don't match: When building series from R list; some parsed sub-elements did not match: One element was f64 and another was list[f64]
```
=> fix: nested null data type Series treated as an empty Series

R/dataframe__frame.R, man/pl_DataFrame.Rd, tests/testthat/test-as_polars.R
A follow up for #1022
Currently in the main branch, there are two functions for building DataFrame from data.frame, and each one handles list columns differently due to the changes made in #1022.
``` r
data = data.frame(a = I(list(data.frame(b = 1))))
polars::as_polars_df(data)
#> shape: (1, 1)
#> ┌─────────────────┐
#> │ a               │
#> │ ---             │
#> │ list[struct[1]] │
#> ╞═════════════════╡
#> │ [{1.0}]         │
#> └─────────────────┘
polars::pl$DataFrame(data)
#> shape: (1, 1)
#> ┌─────────────────┐
#> │ a               │
#> │ ---             │
#> │ list[list[f64]] │
#> ╞═════════════════╡
#> │ [[1.0]]         │
#> └─────────────────┘
```
<sup>Created on 2024-04-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
Since `pl$DataFrame()` may process a variety of …
=> refactor: `pl$DataFrame(<data.frame>)` uses `as_polars_df()`

NEWS.md
Followup of #1027
Mainly two things:
* split breaking changes related to matching the py-polars in API in 4 categories. @eitsupi I'm not sure that's what you meant by "it would be easier to read if they were further categorized" in #1027 but I think it makes sense
* split new features by type of feature (function, method, etc.)
Let me know if that's fine for you or if you prefer #1027 
(PS: the bullet numbers must be 1, 2, 3 and 4 and not a, b, c, d. `mkdocs` automatically convert the 1-4 to a-d but using letters directly doesn't work)
=> Reformat changelog

NEWS.md, R/io_csv.R, tests/testthat/test-csv-read.R
=> fix: store URLs in environment to avoid issues with long filenames

R/dotdotdot.R, R/error__rpolarserr.R
Fix spacing when several strings in `Err_plain()`. Also, I don't understand what the "Some names seen" message means and I don't think it makes the error message better so I suggest we remove it.
Old:
```r
> pl$when(a = 1)
Error: Execution halted with the following contexts
0: In R: in pl$when():
0: During function call [pl$when(a = 1)]
1: Detected a named input.This usually means that you've used `=` instead of `==`.Some names seen:a
```
New:
```r
> pl$when(a = 1)
Error: Execution halted with the following contexts
0: In R: in pl$when():
0: During function call [pl$when(a = 1)]
1: Detected a named input. This usually means that you've used `=` instead of `==`.
```
=> Minor improvement in error messages

.github/workflows/release-lib.yaml
Currently, just after the release of R 4.4.0, R devel on Windows seems to fail to install `stringi`.
This is preventing the release, so I will skip this check.
=> ci: exclude R devel on windows from binary library check step

.github/workflows/docs.yaml
Close #932
Once this merged, I will update https://github.com/rpolars/rpolars.github.io to redirect to the new URL.
I would like to update the URLs in the source code afterwards.
=> ci: deploy the API document to GitHub Pages of this repo instead of rpolars/rpolars.github.io

DESCRIPTION, R/extendr-wrappers.R, R/pkg-arrow.R, R/pkg-nanoarrow.R, man/S3_as_arrow_table.Rd, man/S3_as_nanoarrow_array_stream.Rd, man/S3_as_record_batch_reader.Rd, man/S3_infer_nanoarrow_schema.Rd, src/rust/src/arrow_interop/to_rust.rs, src/rust/src/rdataframe/mod.rs, src/rust/src/rlib.rs, tests/testthat/test-pkg-arrow.R, tests/testthat/test-pkg-nanoarrow.R
Close #781
Part of #732 (Delete unused internal function `export_df_to_arrow_stream`)
I am planning to work on transplanting `OwnedDataFrameIterator` upstream, thus this is a preliminary step.
=> feat: allow to export polars internal types via the Arrow C Stream interface of DataFrame

.github/actions/setup/action.yaml
Builds on Windows are failing frequently with the following error (For example, in #1083).
```log
info: checking for self-update
info: downloading self-update
task: [setup-rust-toolchain] rustup default nightly-2024-04-15-gnu
warning: tool `rust-analyzer` is already installed, remove it from `C:\Users\runneradmin\.cargo\bin`, then run `rustup update` to have rustup manage this tool.
error: could not remove 'setup' file: 'C:\Users\runneradmin\.cargo\bin/rustup-init.exe': Access is denied. (os error 5)
warning: tool `rustfmt` is already installed, remove it from `C:\Users\runneradmin\.cargo\bin`, then run `rustup update` to have rustup manage this tool.
task: Failed to run task "setup-rust-toolchain": exit status 1
warning: tool `cargo-fmt` is already installed, remove it from …
```
=> ci: fix CI falure on Windows

R/expr__name.R, man/ExprName_map.Rd
I'd like to find a solution for `$name$map()`, I'm not sure `$rename()` would do the same thing but I need to think more about this. In the meantime I disable its examples since they fail on CI and prevent the website to be updated. This failure is weird since I had put `@examplesIf FALSE` in a previous PR so it shouldn't be evaluated, but apparently it still is.
=> Temporarily disable examples for `$name$map()`

NEWS.md, R/functions__eager.R, man/pl_concat.Rd
=> feat!: don't rechunk by default in `pl$concat()`

src/rust/Cargo.toml
this enables git import of `r-polars` in other rust based R libraries
`Cargo.toml`
```toml
[package]
name = "test-import"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["rlib", "staticlib"]
[dependencies]
r-polars = { git = "https://github.com/ju6ge/r-polars", branch = "feature/enable-rust-git-import" }
extendr-api = { git = "https://github.com/extendr/extendr", rev = "1895bfc8ee22347665900caa0e48da4f0b13232f" }
```
`lib.rs`
```rust
use r_polars::rdataframe::RPolarsDataFrame;
use extendr_api::prelude::*;
#[extendr]
/// @export
pub fn export_dataframe() -> RPolarsDataFrame {
RPolarsDataFrame::default()
}
extendr_module! {
mod polars_export;
fn export_dataframe;
}
```
=> allow the crate to be build as rust library

NEWS.md, src/rust/Cargo.lock, src/rust/Cargo.toml
Very few new commits compared to the unreleased version in #1147 but at least we have a changelog now: https://github.com/pola-rs/polars/releases/tag/rs-0.41.3
=> Bump to rust-polars 0.41.3

README.Rmd, README.md, vignettes/install.Rmd
Close #1151
Related to #1152, I hope to be able to use GitHub pre-releases in the future to install rewritten versions of the polars package from the rpolars repo.
r-multivese is always tied to the latest release, but rpolars repo can be tied to specific git tag, so pre-releases are ignored by r-multivesre and only rpolars can be updated.
(of course, we will need to call for a switch in installation approach on the NEWS file before that can happen).
@shikokuchuo says that the R-multiverse community universe (<https://community.r-multiverse.org/builds>) is ready for use, but will not be actively promoted until the production universe (<https://production.r-multiverse.org/builds>) is complete.
=> docs: use r-multiverse repo instead of rpolars repo for installing the latest release version

README.Rmd, README.md, vignettes/install.Rmd
@eitsupi sorry I didn't notice until you'd merged #1159.
For the installation instructions, the URL to use should be <https://community.r-multiverse.org>.
I've amended it for you in the places you had changed.
=> Point to canonical URL for R-multiverse

tests/testthat/test-extendr-meta.R
The release of the binary library failed because this test failed on R devel, possibly due to not updating the extendr (#1154).
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-extendr-meta.R:7:3'): clone_robj + mem_adress ──────────────────
Error in `mem_address(robj)`: R_ExternalPtrAddr: argument of type ENVSXP is not an external pointer
Backtrace:
▆
1. ├─testthat::expect_identical(pl$mem_address(env), pl$mem_address(env2)) at test-extendr-meta.R:7:3
2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
4. └─pl$mem_address(env)
5.   └─polars:::mem_address(robj)
```
=> test: tempolary disable the test of `pl$mem_address`

R/dataframe__frame.R, R/polars_envvars.R, R/utils.R, inst/misc/develop_polars.R, tests/testthat/helper.R, tests/testthat/test-Rerr.R, tests/testthat/test-as_polars.R, tests/testthat/test-csv-read.R, tests/testthat/test-dataframe.R, tests/testthat/test-expr_expr.R, tests/testthat/test-expr_name.R, tests/testthat/test-groupby.R, tests/testthat/test-lazy.R, tests/testthat/test-rbackground.R, tests/testthat/test-series.R, tests/testthat/test-whenthen.R
Using `flint::fix_package(exclude_linters = "equal_assignment")`
Most changes are about using specialized `expect_` functions but there are a few QoL changes as well (using leading 0 for decimals, replacing T/F by TRUE/FALSE, etc.)
=> refactor: fix some lints

DESCRIPTION, NEWS.md, src/rust/Cargo.lock, src/rust/Cargo.toml, src/rust/src/lazy/dataframe.rs, src/rust/src/rdataframe/mod.rs, tests/testthat/test-parquet.R
This fixes an annoying bug in `$scan_parquet()` (see uncommented test) and there were just a few commits since 0.42.0
=> Bump rust-polars to unreleased version

NEWS.md, R/extendr-wrappers.R, R/io_parquet.R, man/IO_read_parquet.Rd, man/IO_scan_parquet.Rd, src/rust/src/rdataframe/read_parquet.rs, tests/testthat/test-parquet.R
Add two arguments already in `$scan_ipc()` for better handling of hive partitions. There are some bugs upstream (see tests commented out) but we can already add support for those.
=> Better handling of hive partitions in `$scan_parquet()`

DESCRIPTION, NEWS.md, configure, src/Makevars.in, src/rust/Cargo.toml, tools/lib-sums.tsv
Error seen in ubuntu CI workflow of tidypolars
=> fix: add `-z noexecstack` in Makevars

NEWS.md
@etiennebacher As far as etiennebacher/tidypolars#137 is concerned, I don't think the cause of your CI failure is related to the update, so I think the document needs to be changed.
=> docs(news): remove misleading expressions to users

NEWS.md, R/dataframe__frame.R, src/rust/Cargo.lock, tests/testthat/test-dataframe.R
=> fix: do not error when converting datatype `Null` to R

.github/workflows/flake.yml, flake.lock
Fixes https://github.com/pola-rs/r-polars/issues/1231#issuecomment-2351481317
The nix flake lockfile needed an update to support the version of rust r-polars uses. 
Nix build should work after this.
=> ci: set GHA for updating flake.lock

cleanup.win, configure
R CMD check now checks to see if the rustc version is shown in the installation log, so even if rustc is not used, the version must be shown.
https://github.com/r-devel/r-svn/commit/6114d4126434c056b476cbc5db2657536c153d9a
I saw this warning at <https://github.com/eitsupi/r-glaredb/actions/runs/10879498825/job/30184319369>
```log
❯ checking Rust compilation ... WARNING
No rustc version reported prior to compilation
```
In addition, remove the unnecessary flag added by #1212.
=> fix: ensure report rustc version if pre-built binary will be used

DESCRIPTION, tests/testthat/test-pkg-nanoarrow.R
It seems that the test is starting to fail due to nanoarrow updates in R-multiverse.
=> test: the latest nanoarrow supports utf8view type

DESCRIPTION, R/pkg-knitr.R
Related to #1283
`knitr:::escape_html` was replaced by `xfun::html_escape`
See mgondan/mathml#18
=> fix: replace `knitr:::escape_html` by `xfun::html_escape`

R/io_csv.R
Fix #1288
The help of `download.file` says:
> Code written to download binary files must use mode = "wb" (or "ab"), but the problems incurred by a text transfer will only be seen on Windows.
=> fix: fix csv download issue on windows

DESCRIPTION, NEWS.md
Hot-fix release for R-multiverse to include bcefdc4360cc4840db754fba19d765f68d7a7854 and 08933503273c2a3fe28f7baa87b0afebeeb3a3c1
Context: r-multiverse/help#132
=> release: 0.22.1

README.Rmd, README.md
Might be a bit late but I just realized that the warning message was only displayed in the changelog and releases page, and I doubt many people check those.
So even if it's for a few weeks only, I'd like to show that the package is not abandoned.
=> docs: Add warning about maintenance mode in README

NEWS.md, R/series__series.R
It appears that `unlist()` is failing on R 4.5 due to incorrectly positioned arguments.
=> fix: fix arguments that were erroneously passed outside of `unwrap()`

DESCRIPTION, src/rust/Cargo.lock, src/rust/Cargo.toml, tools/lib-sums.tsv
Related to #1105
Since the new release of extendr contained some breaking changes that cannot be applied here (#1154, #1164, #1187), I cherry-picked only the relevant commits in the fork (rpolars/extendr#5).
Before:
```log
* checking compiled code ... WARNING
Warning: File ‘polars/libs/polars.so’:
Found non-API calls to R: ‘BODY’, ‘CLOENV’, ‘DATAPTR’, ‘ENCLOS’,
‘ENVFLAGS’, ‘FORMALS’, ‘FRAME’, ‘HASHTAB’, ‘PRCODE’, ‘PRENV’,
‘PRSEEN’, ‘PRVALUE’, ‘Rf_allocSExp’, ‘Rf_findVarInFrame3’,
‘SET_BODY’, ‘SET_CLOENV’, ‘SET_ENCLOS’, ‘SET_ENVFLAGS’,
‘SET_FORMALS’, ‘SET_PRCODE’, ‘SET_PRENV’, ‘SET_PRVALUE’,
‘STRING_PTR’, ‘SYMVALUE’, ‘XLENGTH_EX’
These entry points may be removed soon:
‘PRSEEN’, ‘SYMVALUE’
```
This PR:
```log
* checking compiled code ... NOTE
File ‘polars/libs/polars.so’:
Found non-API …
```
=> fix: bump extendr and libR-sys to remove non-api calls warnings on R 4.5.0

inst/misc/filter_rcmdcheck.R
=> ci: ignore NOTE for non-API call on R CMD check on R 4.5

.github/workflows/check.yaml
There is no active development on this package, so there is no need to be aware of new NOTEs anymore.
Context: https://github.com/pola-rs/r-polars/issues/80#issuecomment-1475223652
=> ci: stop using `filter_rcmdcheck.R` to simplify maintenance

.github/workflows/check.yaml
- Remove R devel on Windows, since checking with R devel on Windows tends to be much slower than checking with R devel on Ubuntu and does not provide additional information.
- The check on R 4.5.0 will be added to the matrix, as it is important to be able to pass the check on R 4.5.0, as it is related to whether or not to enter the production repository of the R-multiverse.
=> ci: drop R devel on windows, add R next (4.5.0 beta for now) on ubuntu to check to pass on R 4.5.0

.github/workflows/check.yaml, src/Makevars.in, src/Makevars.win
Context: yutannihilation/savvy#355
It is required by R 4.5.0's R CMD check.
=> fix: remove STATLIB immediately after immediate build

DESCRIPTION, man/polars-package.Rd
I expect the next release to be the last release of this package and would like to clarify support responsibilities by crediting me as the maintainer instead of @sorhawell who is no longer active.
(Just for the record, this was the case in the polars package on CRAN, but I have revert to the original because we gave up on the CRAN release.)
https://github.com/cran/polars/blob/a4763e6c99a7985d3272691535769d0fd529faf5/DESCRIPTION#L6-L10
Related to #1152 and #1336
=> chore: switch the maintainer of this package

R/lazyframe-frame.R
It doesn't seem to work well when combined with `!!!`.
``` r
f <- function(...) {
..1
}
f(!!!c())
#> Error in !c(): invalid argument type
```
I've noticed this in #1474.
The reason is unknown, but it worked in the test before the fix, so no test was added.
=> fix: `..1` etc. (like `...elt(n)`) should not be used with dynamic dots

.github/workflows/build-docs.yml
It might make sense to also create releases of the binary lib to use GitHub's new immutable release feature, and if we do something like this, we don't want this workflow to be triggered on every release.
=> ci(build-docs): Replace the `release` trigger to the `push.tag` trigger with tag name filter

.github/workflows/test-r.yml
Speed up R CMD check on R devel 16m 54s to 7m 2s.
(https://github.com/pola-rs/r-polars/actions/runs/18317354578/job/52161180114?pr=1584 to https://github.com/pola-rs/r-polars/actions/runs/18317857321/job/52162932691?pr=1585)
=> ci(test-r): Skip building rust lib after bin lib release on R CMD check jobs
